-- create tables
create table etudiant (
	id		number generated by default on null as identity constraint etudiant_id_pk primary key,
	nom		varchar(4000 char) constraint etudiant_nom_,
	prenom		varchar(4000 char) constraint etudiant_prenom_,
	DDN		date constraint etudiant_DDN_ constraint etudiant_DDN_,
	filiere		number constraint etudiant_filiere_fk references filiere on delete cascade constraint etudiant_filiere_
)
;

--comments
comment on table etudiant is 'etudiant ';
comment on column etudiant.DDN is 'date de naissance';

create table filiere (
	id		number generated by default on null as identity constraint filiere_id_pk primary key,
	nom		varchar(4000 char) constraint filiere_nom_cc check (nom in ('GL','IWIM','BI')) constraint filiere_nom_,
	nombre_des_etudiants		integer constraint filiere_nombre_des_etudiants_
)
;


-- table index
create index etudiant_1 on etudiant (DDN);

-- create views
create or replace view v1 as 
select
	etudiant.nom						etudiant_nom,
	etudiant.prenom						etudiant_prenom,
	etudiant.DDN						etudiant_DDN,
	etudiant.filiere						etudiant_filiere,
	filiere.nom						filiere_nom,
	filiere.nombre_des_etudiants						filiere_nombre_des_etudiants
from 
	etudiant,	filiere
where 

/

-- load data
select
	nom,
	prenom,
	DDN,
	filiere
from etudiant;

